pipelines:
  Build_ffmpeg:
    group: ffmpeg
    label_template: "${repository[:8]}"
    materials:
      repository:
        git: git@github.com:sebastianhutter/docker-ffmpeg.git
    timer:
      spec: "0 0 1 1/7 * ?"
      only_on_changes: no
    stages:
      - Build:
          jobs:
            build:
              artifacts:
               - build:
                   source: image_version
              tasks:
               - exec:
                   command: make
                   arguments:
                    - build_latest
               - exec:
                   command: make
                   arguments:
                    - build_commit
               - exec:
                   command: make
                   arguments:
                    - push_latest
               - exec:
                   command: make
                   arguments:
                    - push_commit